# Generated by Django 4.0.3 on 2022-04-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(default='Needs to be added', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(default='Needs to be added', max_length=50),
            preserve_default=False,
        ),
    ]
