# Generated by Django 4.0.3 on 2022-04-11 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=100)),
                ('total_occupancy', models.IntegerField()),
                ('total_bedrooms', models.IntegerField()),
                ('total_bathrooms', models.IntegerField()),
                ('room_description', models.TextField()),
                ('has_kitchen', models.BooleanField()),
                ('has_wifi', models.BooleanField()),
                ('has_tv', models.BooleanField()),
                ('has_air_conditioning', models.BooleanField()),
                ('has_heating', models.BooleanField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('room_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms',
                'ordering': ['-published_date'],
            },
        ),
    ]
