# Generated by Django 4.0.3 on 2022-04-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='total_bathrooms',
            field=models.FloatField(),
        ),
    ]
